In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot('just loved it!',30) #the sentence "just loved it!" will be assigned a number on its defined vocab size

[24, 19, 18]

In [ ]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[18, 28], [5, 6], [2, 4], [24, 19, 18], [19, 21, 25], [11, 28], [14, 21, 24], [19, 14], [19, 10], [20, 13]]


In [ ]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews) #padding considering the maximum sentence size(want each encoded vector have equal no. of elements)

[[18 28  0]
 [ 5  6  0]
 [ 2  4  0]
 [24 19 18]
 [19 21 25]
 [11 28  0]
 [14 21 24]
 [19 14  0]
 [19 10  0]
 [20 13  0]]


In [ ]:
embedded_vector_size = 5
model= Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length,name="embedding")) #first layer that is embedding layer 
model.add(Flatten())# second layer that is concating the vectors 
model.add(Dense(1, activation='sigmoid'))# one neuron layer

In [ ]:
X= padded_reviews
y= sentiment

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X,y, epochs=50, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 179ms/step - loss: 0.6098 - accuracy: 1.0000


In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[ 0.01797991, -0.08072254,  0.07653565,  0.05748725, -0.01391844],
       [-0.01079993,  0.00315057,  0.04125741, -0.00838663,  0.04934723],
       [-0.04784485,  0.07531904, -0.00625606, -0.0903423 ,  0.05738634],
       [ 0.03243729,  0.04616772,  0.02266562,  0.01706708,  0.02953032],
       [-0.05675121, -0.02778028,  0.09981415, -0.0890925 ,  0.05862622],
       [-0.09073552,  0.09277928, -0.0138536 , -0.06399844,  0.09717562],
       [-0.08635537, -0.08830216,  0.0478397 , -0.07085932,  0.07512259],
       [ 0.01450684,  0.0182076 , -0.03604413,  0.01214238, -0.01362543],
       [-0.03036962,  0.03714572,  0.00472493, -0.02627853, -0.01749219],
       [-0.02287999,  0.01686385, -0.0176913 ,  0.02052268,  0.04808876],
       [ 0.07828232,  0.10039411, -0.02335182,  0.06515408, -0.05791279],
       [ 0.09226397, -0.07197367,  0.0220069 ,  0.00842187, -0.07806485],
       [-0.03691484,  0.03785744, -0.04587975,  0.0464207 , -0.00692219],
       [ 0.06180521,  0.05126006, -0.0